### ISSUE TITLE
[Feature Request] Add support for `NX_CLOUD_ACCESS_TOKEN`

### ISSUE THREAD

**Issue by warnellw** [nrwl/ci#14]
Hey there!

In our Nx GitHub Actions setup we currently set the `NX_CLOUD_ACCESS_TOKEN` environment variable to a token that has read/write access, while our local development environments use a read-only token (docs [here](https://nx.app/docs/manage-access#security-concerns-and-setups)). Is it possible to set a different Nx Cloud token utilizing this workflow?

I apologize if this is considered a duplicate, and I did see issue #8 asking about general environment variables. However, this seems a little more specific because it's an advertised feature of Nx Cloud.

Thank you!

**Comment by warnellw** [comment]
So I've not actually tried this, but I'm wondering if it's possible to add a `NX_CLOUD_ACCESS_TOKEN` `input` to the `nx-cloud-agents` and `nx-cloud-main` workflows, then set an environment variable equal to that value on the runner?

**Comment by JamesHenry** [comment]
Hi @warnellw, we added support for forwarding the `NX_CLOUD_ACCESS_TOKEN` secret into the workflow, please see the updated README https://github.com/nrwl/ci/blob/38a699623acaa7c2887edc5f7739cbb0388bc038/README.md#adding-read-write-nx-cloud-access-token-to-workflow

PR was #20
