### ISSUE TITLE
Support yarn v2+

### ISSUE THREAD

**Issue by Wykks** [nrwl/ci#24]
I noticed a cache issue with yarn v2+:

https://github.com/nrwl/ci/blob/38a699623acaa7c2887edc5f7739cbb0388bc038/.github/workflows/nx-cloud-agents.yml#L123-L126

 `yarn cache dir` doesn't exist in yarn 2+

This should be done instead: 

https://github.com/actions/cache/blob/main/examples.md#node---yarn-2

Edit: also `--immutable` should be used instead of `--frozen-lockfile` at the install step

**Comment by meeroslav** [comment]
Nx at the moment does not support fully yarn berry, so even if you would fix this there's a chance your install would not work.

Hopefully, we will have the support soon.

**Comment by Wykks** [comment]
It's actually working: https://github.com/Wykks/ngx-mapbox-gl/actions/runs/2810203839
Just not using the cache.

I'm aware that nx doesn't support yarn berry fully because of pnp mode.
But with the "nodeLinker: node-modules" mode, I don't see any reason to prefer yarn v1 instead of yarn berry.

Welp, I can live with no cache :)

**Comment by Michsior14** [comment]
The current version of yarn berry (3.2.4) and cache check doesn't work anymore:
https://github.com/Michsior14/ngrx-addons/actions/runs/3436100975/jobs/5729233284

**Comment by meeroslav** [comment]
@Michsior14 cache check never worked, check https://github.com/nrwl/ci/issues/24#issuecomment-1209827924

That's why the issue is still open. Hopefully we'll get to it soon

**Comment by Michsior14** [comment]
@meeroslav Yep I know, what I meant is that it was working fine (without the cache) in the past, but since v3.2.4 the pipelines fails due to the wrong command in the cache check. Sorry for confusion ;)

**Comment by meeroslav** [comment]
Oh, ok, we'll have a look at it as soon as possible
