### ISSUE TITLE
Use {{ input.runs-on }} instead of ubuntu-latest for self-hosted option

### ISSUE THREAD

**Issue by FaisalAfroz** [nrwl/ci#26]
https://github.com/nrwl/ci/blob/5951d726fbdd056a1ae4184b3b31fa7db5b2f2db/.github/workflows/nx-cloud-agents.yml#L66

**Comment by FaisalAfroz** [comment]
It is already being used in https://github.com/nrwl/ci/blob/5951d726fbdd056a1ae4184b3b31fa7db5b2f2db/.github/workflows/nx-cloud-agents.yml#L50

**Comment by meeroslav** [comment]
Thank you for reporting this @FaisalAfroz. 

We somehow missed this one. Fix is on the way!
