### ISSUE TITLE
How to get outputs from nx-cloud-main workflow?

### ISSUE THREAD

**Issue by PodStuart** [nrwl/ci#37]
I've been trying to see if it is possible to execute a command within the nx-cloud-main workflow and send the result to $GITHUB_OUTPUT and then pick it up later on in our pipeline. 

Our use case is to drive a strategy matrix with a list of affected projects with a "package" target which in our case means that the project needs to be pushed to ECR and deployed to ECS. We have this working already with a custom action but it requires a fair bit of copy/paste from the nx-cloud-main workflow which is a bit of a maintenance overhead to keep up to date.

I don't think this is possible with a reusable workflow (a GitHub limitation not an Nx one) but I am hoping to be proved wrong.

Thanks in advance.

**Comment by bdebon** [comment]
We would like to know exactly the same thing.
Actually, we would like to use the generated code coverage by `nx-cloud-main` workflow in our codecov workflow.
Right now, I have no idea how to do that...

![CleanShot 2022-10-31 at 14 39 57@2x](https://user-images.githubusercontent.com/6163954/199021531-98ba037b-27e3-40bf-8645-7121b081b121.jpg)

**Comment by PodStuart** [comment]
I would say you have a separate question and should raise a separate issue. You are asking how to hook the nx cloud workflow up with build artifacts. It would be a good enhancement to allow the dist folder to be uploaded as an artifact.

**Comment by bdebon** [comment]
Hey @PodStuart, you are right, I'm gonna open another issue to ask for artifacts upload implementation. Thank you for the recommendation and I hope you will find a solution to your problem!

**Comment by meeroslav** [comment]
Hi @PodStuart, unfortunately as you suspected this is not possible due to the limitation of the reusable workflows.

Since a lot of folks have custom requirements that don't really fit the minimal intention of this workflow, we will add an example of a manual GitHub workflow with distributed task execution setup, so that you can copy-paste that and expand from there.
