### ISSUE TITLE
Permission denied error with GitHub Actions when using pnpm

### ISSUE THREAD

**Issue by leggomuhgreggo** [nrwl/ci#38]
## Overveiw

The `nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8` and `nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8` actions don't seem to work with `pnpm`.

### Details

When I tried using the generated GitHub Actions workflow while using `pnpm` I encountered this error.

```
sh: 1: nx-cloud: Permission denied
Error: Process completed with exit code 126.
```

<details>
  <summary>workflow code</summary>

  ```js
name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    secrets: inherit
    with:
      number-of-agents: 3

      init-commands: |
        pnpm exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
        pnpm exec nx-cloud record -- pnpm exec nx format:check
      parallel-commands-on-agents: |
        pnpm exec nx affected --target=lint --parallel=3
        pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
        pnpm exec nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    secrets: inherit
    with:
      number-of-agents: 3

  ```
</details>

<img width=300 src=https://user-images.githubusercontent.com/2213636/198911863-3104c1a2-9bf5-4dc1-86d2-91153df60ba2.png>

## Troubleshooting

I tried everything I could think of
- adding `secrets: inherit`
- explicitly defining `NX_CLOUD_ACCESS_TOKEN`, `NX_CLOUD_AUTH_TOKEN` in `environment-variables`
- `nx-cloud.env`
- reducing the number of agents / parallelism
- different versions of the actions
- etc

### Works with `yarn`

Eventually I switched to yarn and it worked.

<img width=300 src=https://user-images.githubusercontent.com/2213636/198912036-a0e62687-eb53-4252-8c24-6bd7cfd77226.png>

**Comment by meeroslav** [comment]
That is very strange. Do you have a minimal reproduction where I can see your config?

The error you got doesn't seem to be related to pnpm.

**Comment by JamesHenry** [comment]
I can see in the output that you are using `npx` to invoke `nx-cloud`.

I imagine this caused the problem as `npx` probably couldn't resolve the package locally based on how `pnpm` stores the `node_modules`. 

You should be running `pnpm nx-cloud ...` instead.

**Comment by JamesHenry** [comment]
Whoops, sorry I've just seen that we have `npx` specified on our side. So that cannot be the issue, as we have always been able to integration test this usage with `pnpm` successfully.

~~Reopened and still awaiting a reproduction of the issue from @leggomuhgreggo~~

UPDATE: @meeroslav @leggomuhgreggo had actually already provided his config above - it was visually hidden

**Comment by JamesHenry** [comment]
@meeroslav It's probably not related to this error, but the inclusion of `pnpm exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3` seems undesirable given the workflow already always executes that? Is the above config what we are generating for folks via the `ci` generator?

**Comment by meeroslav** [comment]
@JamesHenry sorry I missed those messages.

Yes, we are generating that line via the `ci` generator. We need to make [this step](https://github.com/nrwl/ci/blob/main/.github/workflows/nx-cloud-main.yml#L288-L289) a bit smarter to skip it if init commands already contain `nx-cloud start-ci-run`

**Comment by fforootd** [comment]
Just hit this issue as well with v0.11.3. Switching to yarn resolved it though 😁

**Comment by meeroslav** [comment]
Based on the target repo https://github.com/zitadel/zitadel it seems that you have a rather specific setup which might not work properly. My guess is that `nx-cloud` was brought in as a transitive dependency, so `pnpm` explicitly disabled running it. Yarn has flat structure so anything hoisted in `node_modules` will be accessible.
