### ISSUE TITLE
[Feature Request]: hook the nx cloud workflow up with build artifacts

### ISSUE THREAD

**Issue by bdebon** [nrwl/ci#40]
Hey guys, 

I would like to know if it's currently possible to hook the nx cloud main workflow up with build artifacts?
To put it simple, I use this:
```
parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3
```

And I would like to upload the generated code coverage to codecov via another job.
The problem, I can't use the generated files from the main nx workflow because I did not find any way to upload the artifacts with a command like:

```
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
```

Right now my workaround has been to copy paste all your script, and add a step after the parallel commands have been executed:
```
  - name: Upload coverage to Codecov
    uses: codecov/codecov-action@v3
```

Thank you in advance for your attention 😊

**Comment by mheob** [comment]
That's exactly what I just tried too. This improvement would please me.

**Comment by gperdomor** [comment]
Same problem here, I need to upload the dist folder
