### ISSUE TITLE
Make more clear what causes the job to fail

### ISSUE THREAD

**Issue by stijnvn** [nrwl/ci#46]
The main job fails with `Error: Process completed with exit code 1.` at the end of the output

<img width="924" alt="image" src="https://user-images.githubusercontent.com/35168834/204871266-da5cd9ab-af84-4941-a70e-d24e36a4a18a.png">

It is not clear at all what causes that failure. I tried debugging it and even revert back to a setup without DTE to see that there was a formatting error.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/35168834/204914560-382491aa-da26-449b-8d9c-752bcadcac22.png">

With DTE the formatting error is printed at the start of the console output and it is polluted with these NX_BASE errors. After the formatter error you get the output from the other task. In my case there are more than 4000 lines between the error and the end of the failed step. 

Can it be made more clear what causes the error? Maybe an overview can be provided at the end of the job?

**Comment by JamesHenry** [comment]
Are you using `nx-cloud record --` before your formatting command? That way it will be captured in your Nx Cloud overview and can easily be seen in the Nx Cloud UI

**Comment by stijnvn** [comment]
I am using a slightly modified version of the action from the README of this repository, so I didn't. I have adjusted the format and workspace-lint command and it solves my issue.

It seems that the `nx affected` commands are recorded by default without needing `nx-cloud` record` command or are it the `parallel-commands-on-agents` commands that are recorded by default? Maybe the README can be modified with the record command added where relevant.

**Comment by JamesHenry** [comment]
Thanks @stijnvn this is a good call out, we should be using `nx-cloud record` in the example in the README.

Anything that goes through the task-runner is recorded automatically (i.e. anything that starts with `nx run`/`nx run-many`/`nx affected --target`). `nx format` and `nx workspace-lint` do not go through the task runner and therefore need the `nx-cloud record` in front of them.

I have documented this in #47 thanks again for the feedback
