### ISSUE TITLE
Pass last-successful-event to nrwl/nx-set-shas

### ISSUE THREAD

**Issue by PodStuart** [nrwl/ci#50]
I was wondering if it would make sense to pass github.event_name to nrwl/nx-set-shas from nx-cloud-main.yml?

This defaults to push within nrwl/nx-set-shas.

We have a pipeline which runs off both push and release events. When it runs from a release event it would be preferable if the base and head SHAs where from the previous release and the current release rather than the previous push and the current release.

Thanks in advance.

**Comment by meeroslav** [comment]
Hi @PodStuart,

Sorry for the late reply. We try to keep this workflow as simple as possible. Its purpose was never to address all the scenarios.

For such granular requirements, I would suggest that you build your own workflow where you can then easily configure everything.

**Comment by PodStuart** [comment]
No problem on the slow reply. I totally take your point on this however I would be reluctant to copy our such a large workflow and miss out of future updates. I think perhaps the workflows have grown beyond that initial intent to be as simple as possible, which is a testament to the value they bring.

**Comment by PodStuart** [comment]
Closing this as I do agree it's probably not a sensible default behaviour to implement.
