### ISSUE TITLE
Allow artifact retention period to be configured

### ISSUE THREAD

**Issue by PodStuart** [nrwl/ci#52]
This is a feature request. We recently started using the ability to store artifacts made possible by the artifacts-path parameter to the nx-cloud-main workflow. This has had the knock on effect of significantly increasing our storage costs for artifacts we only need to store short term. 

I don't think GitHub supports this on a per-repository basis (happy to be corrected) and we do not want to lower the organisation wide default. So if we could set on a per-workflow basis that would be ideal.

The upload artifact action which you are using supports this - https://github.com/actions/upload-artifact#retention-period.

**Comment by meeroslav** [comment]
Hi @PodStuart, would you like to propose a PR to solve this?

**Comment by PodStuart** [comment]
I would love to, just a matter of finding the time :)
