### ISSUE TITLE
First test in each library is very slow

### ISSUE THREAD

**Issue by SuneRadich** [nrwl/ci#60]
I am using the `nx-cloud-main.yml` workflow for our runs. Its working fine, splitting up our runs across three agents. However, our Jest tests run very slow. And it seems that the first test in each library takes a long time, and then the rest of the tests run fast.

![Screenshot 2023-02-07 at 09 33 32](https://user-images.githubusercontent.com/1249306/217193531-68d38a0b-b1bb-4a3c-8829-047a0f03d93d.png)

I have tried to play with `--maxworkers` and `--runInBand` but have not seen much of any improvement.

The tests run blazing fast locally, using the same nx command `npx nx run-many --target=test --parallel=3 --all -- --runInBand`

Can this be an issue with the Github workflow, or with nx config - or just the way we use tests?

**Comment by barbados-clemens** [comment]
If you clear the jest cache locally and rerun your tests to they behave the same? 

`npx jest --clearCache`

The cache holds the transformed code which is usually why tests are slow (requiring ESM -> cjs transformations)

**Comment by SuneRadich** [comment]
I have tried that, I do not see the same extreme slowness on the first test in each lib.

**Comment by meeroslav** [comment]
Closing this issue since there was no response for a long time.
