### ISSUE TITLE
When there's a pr that doesn't affect anything in nx build (i.e yml file change, md file etc...) there are no artifacts at all.

### ISSUE THREAD

**Issue by harellevy** [nrwl/ci#70]
When there's a pr that doesn't affect anything in nx build (i.e yml file change, md file etc...) there are no artifacts at all.
In that case the deploy fails on downloading the artifacts...
i.e

<img width="886" alt="image" src="https://user-images.githubusercontent.com/2623446/222196812-96f08ce3-9fd8-4cb0-b5f6-2c09412fcd1d.png">

And in the deploy step I get this error:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/2623446/222198872-f6c2753c-c846-4f2d-8300-75b2645bd7b6.png">

what is the suggested approach to downloading artifacts without getting errors if they are missing?

**Comment by meeroslav** [comment]
I think this is a question best asked at https://github.com/actions/download-artifact.
