### ISSUE TITLE
How do I set environment variables inside of this workflow?

### ISSUE THREAD

**Issue by andersonba** [nrwl/ci#8]
Hey, guys!

I would like to set the `NPM_TOKEN` env var in the nx workflow due to our private repository.
How can I do it? Thanks!

**Comment by JamesHenry** [comment]
Hi @andersonba, I have updated the README to explain a bit more about the intention of this project and its limitations:
https://github.com/nrwl/ci#disclaimer-github-workflow-limitations

Specifically, the limitation you are running into is found here:
https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

In your case the best course of action is take the workflow config we have set up for you and use it (and customize it) directly within your own config.

Best of luck!

**Comment by andersonba** [comment]
@JamesHenry thank you for the explanation!!
