### ISSUE TITLE
Unable to use environment variables in .npmrc with PNPM

### ISSUE THREAD

**Issue by LexanRed** [nrwl/ci#81]
We are using different registries for some packages. 

For example fontawesome.

This is our .npmrc file: 
```
strict-peer-dependencies=false
auto-install-peers=true

@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_TOKEN}
```

Locally I have set a env variable in my .zshrc file, works fine. 
Since as of now it is not possible to use any other secrets than the ones defined under secrets, we defined our tokens in Github variables (not optimal, but for now it is fine). 

Here is our workflow yml file:

```
name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      # NOTE: Here we are using the special `nx-cloud record` command to ensure that any commands we run that do not go through the cloud task runner natively
      # (i.e. anything that starts with `nx run`/`nx run-many`/`nx affected --target`), are still captured in the Nx Cloud UI and Github App comment for
      # easier troubleshooting. See more here: https://nx.dev/nx-cloud/set-up/record-commands#recording-non-nx-commands
      environment-variables: |
        FONTAWESOME_NPM_TOKEN=${{ vars.FONTAWESOME_NPM_TOKEN }} 
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3
```

We tried a lot of combinations regarding the environment-variables, it just does not want to work. 
![Screenshot 2023-04-20 at 13 20 19](https://user-images.githubusercontent.com/57357219/233351052-3a0c097f-a94f-44bf-aad1-8108cc7932d0.png)

If we define our tokens hardcoded in .npmrc, then it works. 

It seems to me like the env variables are not parsed at all. 
Any feedback is very much appreciated.

**Comment by meeroslav** [comment]
Thank you @LexanRed, for reporting this issue.

Can you try to hardcode the token value in workflow yaml?
```
environment-variables: |
  FONTAWESOME_NPM_TOKEN='abcdefg12345'
```

Would that work for you?

Unfortunately, reusable workflows have a lot of restrictions which is why we suggest folks with additional requirements to create their own custom workflow where you can control every aspect.

**Comment by LexanRed** [comment]
I already tried it. Did not change the outcome.

**Comment by meeroslav** [comment]
Unfortunately, this seems to be a limitation of the reusable workflows. We suggest you build your own workflow for this scenario.
