### ISSUE TITLE
Upload Coverage

### ISSUE THREAD

**Issue by AlaaInflyter** [nrwl/ci#84]
Hey ! 
First of all, thanks for the work.
In the example, a --code-coverage is used. Which means coverage files are generated.
The problem is, since the tests are run on the agents, the coverage files are generated there, and are not available on the main job.
How would you upload these coverage files ? (using the codecov action for example)

**Comment by meeroslav** [comment]
With Nx, you need to configure the test target to cache the output (in this case, the coverage).
https://nx.dev/packages/devkit/documents/TargetConfiguration#outputs

Using Nx Cloud caching, the cached coverage will be accessible by any agent (including the main).
