### ISSUE TITLE
Environment variables in custom workflow

### ISSUE THREAD

**Issue by kdawgwilk** [nrwl/ci#92]
CI Provider: GitHub

Where do I set env vars when using a custom workflow for the parallel tasks?  Do I set them on the agent job? if so which step? the Start Nx Agent step?  This didn't seem to be working for me.

**Comment by meeroslav** [comment]
You can't, unfortunately. The custom workflows can only receive the information from the main pipeline via known inputs.

If you need something custom, we advise you to follow the guidelines on https://nx.dev/nx-cloud/recipes/set-up/monorepo-ci-github-actions and create your own workflow from scratch.
