### ISSUE TITLE
pnpm setup fails

### ISSUE THREAD

**Issue by mattlewis92** [nrwl/ci#93]
Hi!

Due to passing `package_json_file` here:

https://github.com/nrwl/ci/blob/40ef06cab594c04b9731f7184b2e92fce59fd4f5/.github/workflows/nx-cloud-agents.yml#L108

and here:

https://github.com/nrwl/ci/blob/40ef06cab594c04b9731f7184b2e92fce59fd4f5/.github/workflows/nx-cloud-main.yml#L132

This causes the "Install PNPM" step to fail with these workflows:
![CleanShot 2023-11-02 at 20 29 01](https://github.com/nrwl/ci/assets/6425649/0832e5d1-d660-4520-b816-efbc5a3268f9)

The problem here is how pnpm appends the workspace root to the input as well, which is how we end up with it there twice:

https://github.com/pnpm/action-setup/blob/d2613e087f2e0aa841925861c5a5f7395d552177/src/install-pnpm/run.ts#L53

Maybe this should be fixed in that action instead?

**Comment by mmjmanders** [comment]
Same here, it would be really nice if this were to be fixed

**Comment by meeroslav** [comment]
Solved by https://github.com/nrwl/ci/pull/94
