### ISSUE TITLE
Additional info on environment variables

### ISSUE THREAD

**Issue by ctjhoa** [nrwl/ci#99]
Hi,

As many, I've struggled a bit to make this reusable workflow compatible with non-hardcoded environment variables.
Related issues:

- https://github.com/nrwl/ci/issues/92
- https://github.com/nrwl/ci/issues/81
- https://github.com/nrwl/ci/issues/44
- https://github.com/nrwl/ci/issues/8

After some digging in GitHub capabilities, I've find out that the [limited secrets support](https://github.com/nrwl/ci?tab=readme-ov-file#limited-secrets-support) can be kinda workaround using "GitHub Variables" instead of "GitHub Secrets".
Here is my detailed blog post:
https://www.qovery.com/blog/github-variables-and-nx-reusable-workflows/

I hope it can help someone to debug their stack.

cc @meeroslav @JamesHenry

I was not sure how to report that info to other users, feel free to close this issue if you don't find that relevant.

**Comment by mandarini** [comment]
Thank you very much @ctjhoa for looking into this, and providing a detailed solution for other users affected by the same limitation! Indeed, I will close this issue now, but it will be easily discoverable by anyone facing the same issue, if they search for it! 

Again, thank you very very much!

If you think I should reopen, let me know. Also, you can definitely post your amazing blog post [on our discord](https://go.nx.dev/community), so maybe someone can find it there too!
